;========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #ea050515
foreground = ${xrdb:color7:#222}
foreground-alt = ${xrdb:color7:#222}
background-alt = ${xrdb:color8:#222}
primary = ${xrdb:color1:#222}
secondary = ${xrdb:color2:#222}
alert = ${xrdb:color3:#222}

[bar/dabar]
width = 100%
height = 20pt
monitor = ${env:MONITOR:}
bottom = true

border-color = ${colors.none}

background = ${colors.background}
foreground = ${colors.foreground}

scroll-up = "#i3.prev"
scroll-down = "#i3.next"

line-size = 3pt

padding-left =  1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.secondary}

font-0 = "NotoSansNerdFont:weight=bold:size=11;2"
font-1 = "Noto Color Emoji:size=8:antialias=true:autohint=true:scale=9;1"

modules-left = xkeyboard i3 weather 
modules-center = playerctl
; updates
modules-right = eth temperature root pulseaudio memory cpu battery tray date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = i3

[bar/others]
width = 100%
height = 20
monitor = ${env:MONITOR:}
bottom = true

border-color = ${colors.none}

background = ${colors.background}
foreground = ${colors.foreground}

scroll-up = "#i3.prev"
scroll-down = "#i3.next"

line-size = 3pt

padding-left =  1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.secondary}

font-0 = "NotoSansNerdFont:weight=bold:size=11;2"
font-1 = "Noto Color Emoji:size=8:antialias=true:autohint=true:scale=9;1"

modules-left = xkeyboard i3 
modules-center = playerctl
; updates
modules-right = date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = i3


[module/i3]
type = internal/i3

pin-workspaces = true
strip-ws-numbers = false
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scrolling = true
fuzzy-match = true

format = <label-state>
label-mode = 
label-mode-padding = 0
label-mode-background = ${colors.background}

label-focused = %name%
label-focused-foreground = ${colors.secondary}
label-focused-background =  
label-focused-underline = ${colors.background-alt}
label-focused-padding = 1

label-visible = %name%
label-visible-padding = 0

label-urgent = %name%
label-urgent-foreground = ${colors.white}
label-urgent-background = ${colors.alert} 
label-urgent-padding = 0

label-unfocused = %name%
label-unfocused-padding = 1

[module/root]
type = internal/fs
interval = 25
warn-percentage = 70

mount-0 = /home

label-mounted = %mountpoint%: %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
sink-input = true

format-volume-prefix = "󱀞 "
format-volume-prefix-foreground = ${colors.disabled}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}

label-muted = muted
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 0
label-indicator-margin = 0
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foam}
label = %used%
label-foreground = ${colors.foam}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.iris}
label = %percentage%%
label-foreground = ${colors.iris}

[network-base]
type = internal/network
interval = 1
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#ff5588}󰈀%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#f0c674}󰖩 %signal%%

[module/eth]
inherit = network-base
interface-type = wired
; %downspeed% | %upspeed%
label-connected = %{F#f0c674}󰈀%{F-}

[module/date]
type = internal/date
interval = 1

format-prefix-foreground = ${colors.foam}

date-alt = %I:%M %p
date = %I:%M %p

label = %date%
label-foreground = ${colors.foam}

[module/battery]
type = internal/battery

full-at = 100
low-at = 5

; $ ls -1 /sys/class/power_supply/
battery = BAT1
adapter = ACAD

poll-interval = 5

format-charging = %{F#a6e3a1}<animation-charging> <label-charging>%{F-}
format-discharging = %{F#a6e3a1}<ramp-capacity> <label-discharging>%{F-} 
label-charging = "%percentage%%"
label-discharging = "%percentage%%"

label-full = %{F#a6e3a1}󱟢 %percentage%%%{F-}
label-low = %{F#FF0000}󰂃 %percentage%%%{F-}
; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 󰁻
ramp-capacity-1 = 󰁽
ramp-capacity-2 = 󰁿 
ramp-capacity-3 = 󰂁 
ramp-capacity-4 = 󰁹

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 󰂆 
animation-charging-1 = 󰂈 
animation-charging-2 = 󰂉 
animation-charging-3 = 󰂊 
animation-charging-4 = 󰂅 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 󰁹 
animation-discharging-1 = 󰂁 
animation-discharging-2 = 󰁿 
animation-discharging-3 = 󰁽 
animation-discharging-4 = 󰁻
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/updates]
type = custom/script
exec = ~/.config/polybar/scripts/updates_script.sh
interval = 500 ; Update every 10 minutes
format = <label>
format-foreground = ${colors.foam}

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather_script.sh
interval = 500 ; Update every 10 minutes
format = <label>
format-foreground = ${colors.foam}

[settings]
screenchange-reload = true
pseudo-transparency = false

[module/playerctl]
type = custom/script
exec = $HOME/.config/polybar/scripts/playerctl.sh
interval = 0.5
label-foreground = #ffffff
; format-background = ${colors.background-alt}
; vim:ft=dosini

[module/tray]
type = internal/tray

format-margin = 8px
tray-spacing = 8px

[module/temperature]
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Thermal zone to use
; To list all the zone types, run 
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 0

; Select thermal zone by name
; The name has to match the contents of /sys/class/thermal/thermal_zone*/type
; for the desired thermal zone.
; New in version 3.7.0
; Default: ""
zone-type = x86_pkg_temp

; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone setting
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 60
